# 开发环境
server:
    port: 8080

database:
    dialect: sqlite
    host: localhost
    port: 3306
    db: test
    userName: root
    password: rootpass
    otherParams: charset=utf8mb4&parseTime=True&loc=Local
    maxIdleConns: 3
    maxOpenConns: 50
    connMaxLifetime: 60

log:
    enableConsole: true
    consoleJSONFormat: false
    consoleLevel: debug
    enableFile: true
    fileJSONFormat: true
    fileLevel: info
    fileLocation: /tmp/myapp/log/info.log
    errFileLevel: error
    errFileLocation: /tmp/myapp/log/error.log
