server:
    port: 8000
    jwtSecret: example666
    # 不需要鉴权的访问路径
    noNeedAuthPath: []

database:
    dialect: mysql
    host: mysql
    port: 3306
    user: root
    pass: rootpass
    db: example
    maxIdleConn: 5
    maxOpenConn: 5
    connMaxLifeTimeSec: 300

log:
    enableConsole: true
    consoleJSONFormat: false
    consoleLevel: debug
    enableFile: true
    fileJSONFormat: false
    fileLevel: debug
    fileLocation: /tmp/log/info.log
    errFileLevel: error
    errFileLocation: /tmp/log/error.log