# 开发环境配置
server:
    port: 8000
    jwtSecret: zh666-dev
    noNeedAuthPath: [
    ]

database:
    dialect: mysql
    host: localhost
    port: 3306
    db: myapp
    userName: root
    password: password
    otherParams: charset=utf8mb4&parseTime=True&loc=Local
    # 最大空闲连接数
    maxIdleConns: 3
    # 最大连接数
    maxOpenConns: 50
    # 连接超时关闭时间,单位:秒
    connMaxLifetime: 60
    log:
        enableConsole: true
        consoleJSONFormat: false
        consoleLevel: debug
        enableFile: false
        fileJSONFormat: false
        fileLevel: info
        fileLocation: /tmp/log/myapp/dbInfo.log
        errFileLevel: error
        errFileLocation: /tmp/log/myapp/dbError.log

log:
    enableConsole: true
    consoleJSONFormat: false
    consoleLevel: debug
    enableFile: false
    fileJSONFormat: false
    fileLevel: info
    fileLocation: /tmp/log/myapp/info.log
    errFileLevel: error
    errFileLocation: /tmp/log/myapp/error.log
